import Modal1 from "./components/Modal";
import Dropdown1 from "./components/Dropdown";
import Sortable1 from "./components/Sortable";
import Caption1 from "./components/Caption";
import TabCard1 from "./components/TabCard";
export const TabCard = TabCard1;
export const Caption = Caption1;
export const Sortable = Sortable1;
export const Modal = Modal1;
export const Dropdown = Dropdown1;